# Generated by Django 2.0.2 on 2018-03-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('z_axis', models.DecimalField(decimal_places=6, max_digits=9)),
                ('event_type', models.CharField(max_length=200)),
            ],
        ),
    ]
