# Generated by Django 2.0.2 on 2018-03-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_datareport_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='datareport',
            name='generator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.User'),
        ),
    ]
