# Generated by Django 2.0.3 on 2018-04-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20180301_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datareport',
            name='event_type',
        ),
    ]
